name: deploy-storybook

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      publish_profile:
        required: true

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: restore
        run: npm ci

      - name: build
        run: npm run build-storybook

      - name: deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.app_name }}
          publish-profile: ${{ secrets.publish_profile }}
          package: "./storybook-static"
