name: main

on: [push]

jobs:
  test:
    uses: ./.github/workflows/prepare.yml

  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
      app_name: asc-owens-app-dev
    secrets:
      publish_profile: ${{ secrets.APP_OWENS_DEV }}
