name: Reusable workflow example

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: restore
        run: npm ci

      - name: test
        run: npm run test:unit
